name: Build Rose VM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # retrive-base-box:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Download rose-srv6-xubuntu-base.box
  #       run: |
  #         wget ${{ secrets.BASE_BOX_URL}}
  #         ls -la
  #         pwd
  #     - name: Archive production artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         path: /home/runner/work/rose-vm-build/rose-vm-build/
  #         name: rose-srv6-xubuntu-base.box
  packer:
    #needs: retrive-base-box
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install python-swiftclient and python-keystoneclient 
        run: |
          pip install python-swiftclient python-keystoneclient
          
      - name: Check swift upload a test file 
        run: |
          cd packer
          swift --os-auth-url ${{ secrets.SWIFT_AUTH_URL }} \
            --os-application-credential-id ${{ secrets.SWIFT_APP_CRED_ID }} \
            --os-application-credential-secret ${{ secrets.SWIFT_APP_CRED_SECRET }} \
            --os-auth-type v3applicationcredential upload rose/ xubuntu-vagrant-vbox-from-boxfile.json

      - name: Download rose-srv6-xubuntu-base.box
        run: |
          cd packer
          wget ${{ secrets.BASE_BOX_URL }}
          ls -la
          pwd

      - name: Checkout tools rose-vm
        uses: actions/checkout@v2
        with:
          repository: netgroup/rose-vm
          path: rose-vm

      # - name: Download artifact result for build step
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: rose-srv6-xubuntu-base.box
      #     path: packer

      - name: Run packer Build
        run: |
          pwd
          cd packer
          packer build xubuntu-vagrant-vbox-from-boxfile.json
          ls -laR
          mv output-vagrant/package.box ../rose-vm/vagrant-from-box-file/rosevm-xubuntu.box
      
      - name: Upload on SWIFT rosevm-xubuntu.box
        run: |
          swift --os-auth-url ${{ secrets.SWIFT_AUTH_URL }} \
            --os-application-credential-id ${{ secrets.SWIFT_APP_CRED_ID }} \
            --os-application-credential-secret ${{ secrets.SWIFT_APP_CRED_SECRET }} \
            --os-auth-type v3applicationcredential upload rose/vm/github rose-vm/vagrant-from-box-file/rosevm-xubuntu.box --object-name rosevm-xubuntu.box
          
      # - name: Archive artifact test file 5mb
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: packer/base-xubuntu-prepare-for-vagrant.sh
      #     name: small

      - name: Run Vagrant up and take a snapshot
        run: |
          cd rose-vm/vagrant-from-box-file/
          vagrant up
          vagrant halt
          vagrant snapshot save default rose_snapshot

      - name: Run packer build ova
        run: |
          cd packer
          packer build export-vbox.json

      - name: Upload on SWIFT rosevm-xubuntu.box
        run: |
          swift --os-auth-url ${{ secrets.SWIFT_AUTH_URL }} \
            --os-application-credential-id ${{ secrets.SWIFT_APP_CRED_ID }} \
            --os-application-credential-secret ${{ secrets.SWIFT_APP_CRED_SECRET }} \
            --os-auth-type v3applicationcredential upload rose/vm/github packer/output-virtualbox-vm/rose-srv6.ova --object-name rose-srv6.ova
      
      # - name: Compress artifact
      #   run: |
      #     zip -r -X rosevm_xubuntu_ova.zip packer/output-virtualbox-vm/

      # - name: Archive artifact ova
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: packer/output-virtualbox-vm/rosevm_xubuntu_ova.zip
      #     name: rosevm_xubuntu_ova
