name: Build Rose VM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download rose-srv6-xubuntu-base.box
        run: wget ${{ secrets.BASE_BOX_URL}}

      - name: Run packer Build
        run: |
          cd packer
          packer build xubuntu-vagrant-vbox-from-boxfile.json
