name: Build Rose VM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  retrive-base-box:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download rose-srv6-xubuntu-base.box
        run: |
          wget ${{ secrets.BASE_BOX_URL}}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          path: base/rose-srv6-xubuntu-base.box
          name: rose-srv6-xubuntu-base.box
  packer:
    needs: retrive-base-box
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Check files
        run: ls -la
      - name: Download artifact result for build step
        uses: actions/download-artifact@v1
        with:
          name: rose-srv6-xubuntu-base.box
          path: packer

      - name: Run packer Build
        run: |
          pwd
          cd packer
          packer build xubuntu-vagrant-vbox-from-boxfile.json
